### ISSUE TITLE
Kick-start to the Scrum Dashboard

### ISSUE THREAD

**Issue by A-I-18** [lrazovic/advanced_programming#19]
# Scrum
https://docs.google.com/spreadsheets/d/1tXNIpNcNKgHHLupI4G7BKNGZQWeTWLm6U_2PlwncmK0/edit?usp=drive_web&authuser=0
https://docs.google.com/spreadsheets/d/1Hy-cB7U99QcU3_ULBK0MzOkUahD6tEgHB5gi5wrqm2s/edit?usp=drive_web&authuser=0
https://www.shimooka.com/v3/agile-project-planning-with-google-docs/
https://scrummastermarc.medium.com/google-sheets-for-sprint-reporting-7a675ace4d79
https://www.metaltoad.com/blog/user-story-insights-using-google-sheets
    ## Function Points
https://sourceforge.net/p/functionpoints/wiki/Function%20Point%20Analysis/?version=32
https://leftpudding.github.io/Function-Point-Spreadsheet/

**Comment by fabform** [comment]
Handy to [find google sheet id](https://fabform.io/a/how-to-find-google-sheet-id)
